apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ .Values.app.name }}